version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_DATABASE: 'java-fx'
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/var/lib/db/mysql/
    networks:
      - mysql-network

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge